// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfE_Y0Gtxal26rn63NIgS75M7Uq-5CUwU',
    appId: '1:716123287038:web:8c90ebdc74fbe1e052e4af',
    messagingSenderId: '716123287038',
    projectId: 'bengkel-sampah-8c4f5',
    authDomain: 'bengkel-sampah-8c4f5.firebaseapp.com',
    storageBucket: 'bengkel-sampah-8c4f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfE_Y0Gtxal26rn63NIgS75M7Uq-5CUwU',
    appId: '1:716123287038:android:8c90ebdc74fbe1e052e4af',
    messagingSenderId: '716123287038',
    projectId: 'bengkel-sampah-8c4f5',
    storageBucket: 'bengkel-sampah-8c4f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfE_Y0Gtxal26rn63NIgS75M7Uq-5CUwU',
    appId: '1:716123287038:ios:8c90ebdc74fbe1e052e4af',
    messagingSenderId: '716123287038',
    projectId: 'bengkel-sampah-8c4f5',
    storageBucket: 'bengkel-sampah-8c4f5.firebasestorage.app',
    iosBundleId: 'com.bengkelsampah.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfE_Y0Gtxal26rn63NIgS75M7Uq-5CUwU',
    appId: '1:716123287038:macos:8c90ebdc74fbe1e052e4af',
    messagingSenderId: '716123287038',
    projectId: 'bengkel-sampah-8c4f5',
    storageBucket: 'bengkel-sampah-8c4f5.firebasestorage.app',
    iosBundleId: 'com.bengkelsampah.app',
  );
}
